spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/tm_core
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

  liquibase:
    change-log: db/changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8123/realms/trainmate/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /api-docs
  override-with-generic-response: false
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "info,health"

server:
  servlet:
    context-path: /api/tm-core
  port: 8989

keycloak:
  auth-server-url: http://localhost:8123
  realm: trainmate
  resource: train-mate
  bearerOnly: true
  enabled: true
  public-client: true
  cors: true
  use-resource-role-mappings: true
  ssl-required: none
