spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/tm_core
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  liquibase:
    change-log: db/changelog-master.xml

springdoc:
  api-docs:
    path: /api-docs
  override-with-generic-response: false
  show-actuator: true


management:
  endpoints:
    web:
      exposure:
        include: "info,health"

server:
  servlet:
    context-path: /api/tm-core

keycloak:
  enabled: false