spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/tm_core
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  liquibase:
    change-log: db/changelog-master.xml
  docker:
    compose:
      enabled: false
  security:
    user:
      name: user
      password: user

springdoc:
  api-docs:
    path: /api-docs
  override-with-generic-response: false
  show-actuator: true

management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "info,health"